### ISSUE TITLE
can't work

### ISSUE THREAD

**Issue by pstanton** [cowang4/immutable#1]
the backspace and delete keys are disabled

**Comment by cowang4** [comment]
Yes, that's the idea of the plugin. It's supposed to disable the backspace and delete keys to help you focus. It was just an experiment. You can re-enable them with Ctrl+Backspace.

**Comment by pstanton** [comment]
but i can't delete the plugin because no delete key!

**Comment by cowang4** [comment]
You can go to the Packages tab in the Settings window and click the uninstall button there. Or try to re-enable the delete key with Ctrl-Backspace.

**Comment by pstanton** [comment]
sorry mate i'm just joking

**Comment by cowang4** [comment]
Figures... well I mean you gotta give me a star now.
